services:
  app:
    build: .
    container_name: task_manager_api
    command: python ./src/run.py
    ports:
      - 5000:5000
    volumes:
    - .:/usr/src/app
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: