"""company model update

Revision ID: 43bc80fc3269
Revises: 290606a4473b
Create Date: 2023-09-04 00:44:22.696881

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43bc80fc3269'
down_revision: Union[str, None] = '290606a4473b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('companies', 'office_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'office_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('companies', 'created_at')
    # ### end Alembic commands ###
