"""task model update

Revision ID: 87fc1dfbdfee
Revises: 4e82e1f1eb0a
Create Date: 2023-09-03 23:17:55.521234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fc1dfbdfee'
down_revision: Union[str, None] = '4e82e1f1eb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'tasks', 'company_users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
