"""user_task model update

Revision ID: b33684e9158d
Revises: 9da28ccb2c33
Create Date: 2023-09-06 21:30:49.629150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33684e9158d'
down_revision: Union[str, None] = '9da28ccb2c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_tasks_user_id_fkey', 'user_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'user_tasks', 'company_users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.create_foreign_key('user_tasks_user_id_fkey', 'user_tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
